config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root "homes#about"
    get "/version" => "homes#version"
    resource :users, only:[:show, :edit, :update]
    resources :grow_plants do
      member do
        get "pick"
        post "complete"
      end
      collection do
        post "register"
      end
    end
    get "/top" => "grow_plants#top"

  end

  devise_for :users, skip: [:passwords],controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }



  namespace :admin do
    resources :plants, except:[:show]
  end

  devise_for :admin, skip: [:registrations, :passwords],controllers: {
    sessions: "admin/sessions"
  }


end

app/models/plant.rb
class Plant < ApplicationRecord
  has_many :grow_plants
  attachment :image

  enum recommend_place:{ 日向:0, 半日陰:1 }

  validates :plant_name, presence: true
  validates :amount, presence: true
  validates :frequency, presence: true
  validates :image, presence: true
end

app/controllers/admin/plants_controller.rb
class Admin::PlantsController < ApplicationController
  before_action :authenticate_admin!


  def index
    @plants = Plant.all
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    if @plant.save
      redirect_to admin_plants_path
    else
      render :new
    end

  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])
    @plant.update(plant_params)
    redirect_to admin_plants_path
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to admin_plants_path
  end

  private

  def plant_params
    params.require(:plant).permit(:plant_name, :image, :frequency, :amount, :advice, :recommend_place)
  end

end

app/helpers/admin/plants_helper.rb
module Admin::PlantsHelper
end

app/views/admin/plants/edit.html.erb
<%= form_with model: @plant, url: admin_plant_path,method: :patch, local:true do |f| %>
  <div class="d-flex align-items-center justify-content-center flex-wrap mt-5">
    <div class="m-2">
  	  <%= attachment_image_tag @plant, :image, :fill, 200, 200, fallback: "karasazu_logo.jpg" %><br />
 	  	<%= f.attachment_field :image %>
    </div>
 		<div class="align-items-center justify-content-center">
			<h2>植物情報編集</h2>
      <table class="table table-border">
        <tr>
          <td><%= f.label :plant_name, "植物名" %></td>
          <td><%= f.text_field :plant_name %></td>
        </tr>
        <tr>
          <td><%= f.label :frequency, "水やり頻度" %></td>
          <td><%= f.text_field :frequency %>日ごと</td>
        </tr>
        <tr>
          <td><%= f.label :amount, "水量" %></td>
          <td><%= f.text_field :amount %></td>
        </tr>
        <tr>
          <td><%= f.label :recommend_place, "推奨環境" %></td>
          <td><%= f.select :recommend_place, Plant.recommend_places.keys.to_a, {}, class: 'form-control'%></td>
        </tr>
        <tr>
          <td><%= f.label :advice, "育成ポイント:" %></td>
          <td><%= f.text_area :advice %></td>
        </tr>
        <tr>
          <td><%= f.submit '更新する', class: "btn btn-outline-primary" %></td>
          <td class="text-right"><%= link_to "削除する",  admin_plant_path(@plant), data: { confirm: '本当に削除しますか？' }, method: :delete, class: "btn btn-outline-danger" %></td>
        </tr>
      </table>
    </div>
  </div>
<% end %>

app/views/admin/plants/index.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-between mb-5">
    <h2>植物情報一覧</h2>
    <div>
      <%= link_to new_admin_plant_path do %>
        <i class="fas fa-plus-circle fa-3x"></i>
      <% end %>
    </div>
  </div>
  <div class="row">
    <% @plants.each do |plant| %>
    <div class="col">
        <div class="d-flex align-items-center justify-content-center">
          <%= link_to edit_admin_plant_path(plant) do %>
            <%= attachment_image_tag plant, :image, :fill, 150, 150 %>
          <% end %>
        </div>
        <div class="d-flex align-items-center justify-content-center mb-5">
          <p><%= plant.plant_name %><p>
        </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/plants/new.html.erb
<%= form_with model: @plant, url: admin_plants_path, local:true do |f| %>
  <div class="d-flex align-items-center justify-content-center flex-wrap mt-5">
  	<div class="m-2">
  		<div><%= attachment_image_tag @plant, :image, :fill, 300, 300 , fallback: "karasazu_logo.jpg" %></div>
  		<div><%= f.attachment_field :image %></div>
  	</div>
    <div class="align-items-center justify-content-center m-2">
	    <h2>植物情報追加</h2>
		  <table class="table table-border">
	      <tr>
          <td><%= f.label :plant_name, "植物名" %></td>
          <td><%= f.text_field :plant_name %></td>
        </tr>
        <tr>
          <td><%= f.label :frequency, "水やり頻度" %></td>
          <td><%= f.text_field :frequency %>日ごと</td>
        </tr>
        <tr>
          <td><%= f.label :amount, "水量" %></td>
          <td><%= f.text_field :amount %></td>
        </tr>
        <tr>
          <td><%= f.label :recommend_place, "推奨環境" %></td>
          <td><%= f.select :recommend_place, Plant.recommend_places.keys.to_a, {}, class: 'form-control'%></td>
        </tr>
        <tr>
          <td><%= f.label :advice, "育成ポイント" %></td>
          <td><%= f.text_area :advice %></td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit '登録する', class: "btn btn-outline-primary" %></td>
        </tr>
      </table>
    </div>
  </div>
<% end %>