config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root "homes#about"
    get "/version" => "homes#version"
    resource :users, only:[:show, :edit, :update]
    resources :grow_plants do
      member do
        get "pick"
        post "complete"
      end
      collection do
        post "register"
      end
    end
    get "/top" => "grow_plants#top"

  end

  devise_for :users, skip: [:passwords],controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }



  namespace :admin do
    resources :plants, except:[:show]
  end

  devise_for :admin, skip: [:registrations, :passwords],controllers: {
    sessions: "admin/sessions"
  }


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>karasazu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/c4cc096aed.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Yusei+Magic&display=swap" rel="stylesheet">

  </head>
  <body>
    <header>
    <% if user_signed_in? %>
      <nav class="navbar navbar-light navbar-expand-md">
        <a class="navbar-brand" href="#">
          <%=link_to top_path do %>
            <%= image_tag 'logo_top.png', class:"logo" %>
          <% end %>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <p class="nav-item active text-center">ユーザー名:<%= current_user.name %></p>
            <li class="nav-item text-center">
              <%= link_to "マイページ", users_path %>
            </li>
            <li class="nav-item text-center">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
            <li class="nav-item text-center">
              <%= link_to "使い方", version_path %>
            </li>
          </ul>
        </div>
      </nav>
    <% elsif admin_signed_in? %>
      <nav class="navbar navbar-light navbar-expand-md">
        <a class="navbar-brand" href="#">
          <%=link_to root_path do %>
            <%= image_tag 'logo_top.png', class:"logo" %>
          <% end %>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <p class="nav-item active text-center">管理者ログイン中</p>
            <li class="nav-item text-center">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
            </li>
          </ul>
        </div>
      </nav>
    <% else %>
      <nav class="navbar navbar-light navbar-expand-md">
        <a class="navbar-brand" href="#">
          <%=link_to root_path do %>
            <%= image_tag 'logo_top.png', class:"logo" %>
          <% end %>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active text-center">
              <%= link_to "ログイン", new_user_session_path %>
            </li>
            <li class="nav-item text-center">
              <%= link_to "新規登録", new_user_registration_path %>
            </li>
          </ul>
        </div>
      </nav>
    <% end %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>